language: kotlin
sudo: false

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

before_script:
  - pip install --user codecov

script:
  - ./gradlew check
  - ./gradlew test

after_success:
  - codecov

branches:
  only:
  - master