language: kotlin
sudo: false

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

before_script:
  - pip install --user codecov

script:
  - ./gradlew check
  - ./gradlew test
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master